-- =============================================================
-- ONGCONNECT STUDENTHELP - SUPABASE/POSTGRESQL
-- Execute este arquivo no SQL Editor do Supabase antes de ligar o front-end.
-- =============================================================

DROP TABLE IF EXISTS auditoria_doacao CASCADE;
DROP TABLE IF EXISTS voluntariado CASCADE;
DROP TABLE IF EXISTS voluntario CASCADE;
DROP TABLE IF EXISTS recurso CASCADE;
DROP TABLE IF EXISTS doacao CASCADE;
DROP TABLE IF EXISTS projeto CASCADE;
DROP TABLE IF EXISTS doador CASCADE;
DROP TABLE IF EXISTS ong CASCADE;

CREATE TABLE ong (
  id_ong BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  cnpj VARCHAR(18) NOT NULL UNIQUE,
  email VARCHAR(120) NOT NULL,
  telefone VARCHAR(20) NOT NULL,
  uf CHAR(2) NOT NULL,
  data_cadastro DATE NOT NULL DEFAULT CURRENT_DATE,
  status VARCHAR(30) NOT NULL DEFAULT 'ativa' CHECK (status IN ('ativa','inativa','em_analise'))
);

CREATE TABLE doador (
  id_doador BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_razao_social VARCHAR(150) NOT NULL,
  tipo_doador VARCHAR(30) NOT NULL CHECK (tipo_doador IN ('pessoa_fisica','pessoa_juridica')),
  cpf_cnpj VARCHAR(18) NOT NULL UNIQUE,
  email VARCHAR(120) NOT NULL,
  telefone VARCHAR(20) NOT NULL,
  consentimento_lgpd BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE projeto (
  id_projeto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_ong BIGINT NOT NULL REFERENCES ong(id_ong),
  nome VARCHAR(150) NOT NULL,
  descricao VARCHAR(500) NOT NULL,
  data_inicio DATE NOT NULL,
  orcamento_previsto NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (orcamento_previsto >= 0),
  meta_atendimento INT NOT NULL DEFAULT 0 CHECK (meta_atendimento >= 0),
  status VARCHAR(30) NOT NULL DEFAULT 'planejado' CHECK (status IN ('planejado','em_andamento','concluido','cancelado')),
  dados_impacto JSONB
);

CREATE TABLE doacao (
  id_doacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_doador BIGINT NOT NULL REFERENCES doador(id_doador),
  id_ong BIGINT NOT NULL REFERENCES ong(id_ong),
  id_projeto BIGINT NULL REFERENCES projeto(id_projeto),
  data_doacao DATE NOT NULL,
  data_registro TIMESTAMP NOT NULL DEFAULT NOW(),
  tipo_doacao VARCHAR(30) NOT NULL CHECK (tipo_doacao IN ('dinheiro','bem','servico','outro')),
  valor NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (valor >= 0),
  descricao VARCHAR(500),
  emitir_recibo BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(30) NOT NULL DEFAULT 'recebida' CHECK (status IN ('recebida','pendente','cancelada','destinada'))
);

CREATE TABLE recurso (
  id_recurso BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_projeto BIGINT NOT NULL REFERENCES projeto(id_projeto),
  nome VARCHAR(150) NOT NULL,
  tipo_recurso VARCHAR(30) NOT NULL CHECK (tipo_recurso IN ('financeiro','material','humano','servico')),
  descricao VARCHAR(500) NOT NULL,
  quantidade INT NOT NULL DEFAULT 0 CHECK (quantidade >= 0),
  valor_estimado NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (valor_estimado >= 0),
  data_alocacao DATE NOT NULL,
  status_utilizacao VARCHAR(30) NOT NULL DEFAULT 'disponivel' CHECK (status_utilizacao IN ('disponivel','utilizado','reservado','encerrado'))
);

CREATE TABLE voluntario (
  id_voluntario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  cpf VARCHAR(14) NOT NULL UNIQUE,
  email VARCHAR(120) NOT NULL,
  telefone VARCHAR(20) NOT NULL,
  habilidades TEXT[] DEFAULT '{}',
  disponibilidade TEXT[] DEFAULT '{}',
  consentimento_lgpd BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE voluntariado (
  id_voluntariado BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_voluntario BIGINT NOT NULL REFERENCES voluntario(id_voluntario),
  id_projeto BIGINT NOT NULL REFERENCES projeto(id_projeto),
  funcao VARCHAR(100) NOT NULL,
  data_inicio DATE NOT NULL,
  hora_inicio TIME NOT NULL,
  hora_fim TIME NOT NULL,
  carga_horaria INT NOT NULL DEFAULT 0 CHECK (carga_horaria >= 0),
  status VARCHAR(30) NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo','encerrado','suspenso'))
);

CREATE TABLE auditoria_doacao (
  id_auditoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_doacao BIGINT NOT NULL,
  acao VARCHAR(30) NOT NULL,
  valor NUMERIC(12,2) NOT NULL,
  data_evento TIMESTAMP NOT NULL DEFAULT NOW(),
  observacao VARCHAR(255)
);

CREATE INDEX idx_projeto_ong_status ON projeto(id_ong, status);
CREATE INDEX idx_doacao_data ON doacao(data_doacao);
CREATE INDEX idx_doacao_doador ON doacao(id_doador);
CREATE INDEX idx_doacao_projeto ON doacao(id_projeto);
CREATE INDEX idx_voluntariado_projeto ON voluntariado(id_projeto);
CREATE INDEX idx_recurso_projeto ON recurso(id_projeto);

CREATE OR REPLACE FUNCTION fn_auditar_doacao()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO auditoria_doacao (id_doacao, acao, valor, observacao)
    VALUES (NEW.id_doacao, 'INSERT', NEW.valor, 'Doacao registrada para ONG ' || NEW.id_ong);
    RETURN NEW;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO auditoria_doacao (id_doacao, acao, valor, observacao)
    VALUES (NEW.id_doacao, 'UPDATE', NEW.valor, 'Status anterior: ' || OLD.status || ' | novo: ' || NEW.status);
    RETURN NEW;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_auditoria_doacao_insert
AFTER INSERT ON doacao
FOR EACH ROW EXECUTE FUNCTION fn_auditar_doacao();

CREATE TRIGGER trg_auditoria_doacao_update
AFTER UPDATE ON doacao
FOR EACH ROW EXECUTE FUNCTION fn_auditar_doacao();

INSERT INTO ong (nome, cnpj, email, telefone, uf, data_cadastro, status) VALUES
('StudentHelp Recife', '12.345.678/0001-90', 'contato@studenthelp.org', '(81)3333-1000', 'PE', '2026-05-01', 'ativa'),
('Rede Solidaria Futuro', '98.765.432/0001-11', 'gestao@redesolidaria.org', '(81)3333-2000', 'PE', '2026-05-04', 'ativa'),
('Instituto Ponte do Saber', '45.777.888/0001-10', 'ponte@saber.org', '(81)3333-3000', 'PE', '2026-05-08', 'ativa');

INSERT INTO doador (nome_razao_social, tipo_doador, cpf_cnpj, email, telefone, consentimento_lgpd) VALUES
('Maria Helena Souza','pessoa_fisica','111.222.333-44','maria@email.com','(81)99911-2233',TRUE),
('Comercial Boa Vista LTDA','pessoa_juridica','22.333.444/0001-55','financeiro@boavista.com','(81)3211-4455',TRUE),
('Joao Pereira','pessoa_fisica','222.333.444-55','joao@email.com','(81)98888-1010',TRUE),
('Instituto Educar Mais','pessoa_juridica','33.444.555/0001-66','contato@educarmais.org','(81)3111-2222',TRUE),
('Ana Beatriz Lima','pessoa_fisica','333.444.555-66','ana@email.com','(81)97777-3333',TRUE),
('Tech Social Brasil','pessoa_juridica','44.555.666/0001-77','social@techbr.com','(81)3222-4455',TRUE),
('Carlos Roberto Nunes','pessoa_fisica','444.555.666-77','carlos@email.com','(81)96666-7777',TRUE),
('Farmacia Vida Plena','pessoa_juridica','55.666.777/0001-88','contato@vidaplena.com','(81)3555-7788',TRUE),
('Renata Albuquerque','pessoa_fisica','555.666.777-88','renata@email.com','(81)95555-8888',TRUE),
('Mercado Popular Recife','pessoa_juridica','66.777.888/0001-99','adm@mercadopopular.com','(81)3444-9999',TRUE),
('Pedro Araujo','pessoa_fisica','666.777.888-99','pedro@email.com','(81)94444-0000',TRUE),
('Grafica Esperanca','pessoa_juridica','77.888.999/0001-00','vendas@graficaesperanca.com','(81)3666-1010',TRUE);

INSERT INTO projeto (id_ong, nome, descricao, data_inicio, orcamento_previsto, meta_atendimento, status, dados_impacto) VALUES
(1,'Apoio Escolar Comunitario','Aulas de reforco para estudantes em vulnerabilidade.','2026-05-10',12000,120,'em_andamento', '{"indicador":"alunos atendidos","meta":120}'),
(1,'Cesta Digital','Doacao de kits tecnologicos para jovens estudantes.','2026-05-15',18000,60,'planejado', '{"indicador":"kits entregues","meta":60}'),
(1,'Biblioteca Viva','Biblioteca itinerante nos bairros.','2026-05-20',7000,200,'em_andamento', '{"indicador":"leitores cadastrados","meta":200}'),
(2,'Inclusao Jovem','Oficinas de tecnologia e cidadania.','2026-06-01',22000,90,'planejado', '{"indicador":"jovens capacitados","meta":90}'),
(2,'Saude em Movimento','Acoes de orientacao basica de saude.','2026-06-05',15000,300,'em_andamento', '{"indicador":"atendimentos sociais","meta":300}'),
(3,'Alimenta Comunidade','Distribuicao de alimentos para familias cadastradas.','2026-06-08',25000,500,'em_andamento', '{"indicador":"familias atendidas","meta":500}'),
(3,'Mentoria de Carreira','Mentorias para jovens em busca do primeiro emprego.','2026-06-10',9000,80,'planejado', '{"indicador":"jovens mentorados","meta":80}'),
(1,'Esporte e Cidadania','Atividades esportivas para criancas e adolescentes.','2026-06-12',11000,150,'planejado', '{"indicador":"participantes","meta":150}');

INSERT INTO doacao (id_doador, id_ong, id_projeto, data_doacao, data_registro, tipo_doacao, valor, descricao, emitir_recibo, status) VALUES
(1,1,1,'2026-05-11','2026-05-11 10:00:00','dinheiro',500,'Doacao para apoio escolar',TRUE,'recebida'),
(2,1,2,'2026-05-12','2026-05-12 11:00:00','dinheiro',2400,'Apoio ao projeto Cesta Digital',TRUE,'recebida'),
(3,1,NULL,'2026-05-16','2026-05-16 15:30:00','bem',0,'Doacao geral de livros',FALSE,'destinada'),
(4,2,4,'2026-06-02','2026-06-02 09:30:00','dinheiro',5000,'Patrocinio de oficinas',TRUE,'recebida'),
(5,1,3,'2026-06-03','2026-06-03 10:20:00','dinheiro',300,'Apoio biblioteca',TRUE,'recebida'),
(6,1,2,'2026-06-04','2026-06-04 14:10:00','bem',0,'Tablets usados em bom estado',TRUE,'destinada'),
(7,2,5,'2026-06-04','2026-06-04 16:40:00','dinheiro',850,'Saude em Movimento',TRUE,'recebida'),
(8,2,5,'2026-06-05','2026-06-05 09:00:00','bem',0,'Kits de higiene',TRUE,'destinada'),
(9,3,6,'2026-06-06','2026-06-06 12:00:00','dinheiro',1200,'Alimentos para familias',TRUE,'recebida'),
(10,3,6,'2026-06-07','2026-06-07 08:30:00','bem',0,'Cestas basicas',TRUE,'destinada'),
(11,3,7,'2026-06-08','2026-06-08 18:20:00','dinheiro',450,'Mentoria de carreira',FALSE,'recebida'),
(12,1,8,'2026-06-09','2026-06-09 13:45:00','servico',0,'Impressao de material esportivo',TRUE,'destinada'),
(1,1,1,'2026-06-10','2026-06-10 10:10:00','dinheiro',250,'Doacao recorrente',TRUE,'recebida'),
(2,1,NULL,'2026-06-11','2026-06-11 11:15:00','dinheiro',1000,'Doacao institucional geral',TRUE,'recebida'),
(4,2,4,'2026-06-12','2026-06-12 09:30:00','dinheiro',1800,'Segunda parcela',TRUE,'recebida'),
(6,1,2,'2026-06-13','2026-06-13 14:20:00','dinheiro',3500,'Equipamentos digitais',TRUE,'recebida'),
(9,3,6,'2026-06-14','2026-06-14 10:00:00','dinheiro',750,'Compra de alimentos',TRUE,'recebida'),
(11,3,NULL,'2026-06-15','2026-06-15 17:00:00','outro',0,'Doacao de networking profissional',FALSE,'destinada');

INSERT INTO recurso (id_projeto, nome, tipo_recurso, descricao, quantidade, valor_estimado, data_alocacao, status_utilizacao) VALUES
(1,'Material didatico','material','Cadernos, apostilas e kits de estudo',120,1800,'2026-05-13','reservado'),
(2,'Tablets educacionais','material','Equipamentos para aulas digitais',20,16000,'2026-05-18','disponivel'),
(3,'Livros infantis','material','Acervo inicial da biblioteca itinerante',300,4500,'2026-05-22','utilizado'),
(4,'Laboratorio movel','servico','Apoio tecnico para oficinas',1,6000,'2026-06-02','reservado'),
(5,'Kits de higiene','material','Produtos de higiene basica',250,3200,'2026-06-05','utilizado'),
(6,'Cestas basicas','material','Alimentos para distribuicao',500,18000,'2026-06-07','reservado'),
(7,'Mentores convidados','humano','Profissionais convidados para orientacao',10,4000,'2026-06-10','disponivel'),
(8,'Uniformes esportivos','material','Coletes e materiais esportivos',150,3500,'2026-06-13','disponivel');

INSERT INTO voluntario (nome, cpf, email, telefone, habilidades, disponibilidade, consentimento_lgpd) VALUES
('Ana Clara Lima','123.456.789-00','ana@email.com','(81)97777-1010',ARRAY['reforco_escolar','matematica'],ARRAY['segunda','quarta'],TRUE),
('Carlos Andre Silva','234.567.890-11','carlos@email.com','(81)96666-2020',ARRAY['tecnologia','logistica'],ARRAY['sabado'],TRUE),
('Beatriz Nunes','345.678.901-22','beatriz@email.com','(81)95555-3030',ARRAY['leitura','administrativo'],ARRAY['terca','quinta'],TRUE),
('Daniel Souza','456.789.012-33','daniel@email.com','(81)94444-4040',ARRAY['saude'],ARRAY['sexta'],TRUE),
('Elisa Martins','567.890.123-44','elisa@email.com','(81)93333-5050',ARRAY['comunicacao'],ARRAY['segunda','sexta'],TRUE),
('Fernando Costa','678.901.234-55','fernando@email.com','(81)92222-6060',ARRAY['logistica'],ARRAY['sabado','domingo'],TRUE),
('Gabriela Rocha','789.012.345-66','gabriela@email.com','(81)91111-7070',ARRAY['juridico','administrativo'],ARRAY['quarta'],TRUE),
('Helio Ramos','890.123.456-77','helio@email.com','(81)90000-8080',ARRAY['tecnologia'],ARRAY['terca','sabado'],TRUE);

INSERT INTO voluntariado (id_voluntario, id_projeto, funcao, data_inicio, hora_inicio, hora_fim, carga_horaria, status) VALUES
(1,1,'Monitora de reforco','2026-05-15','14:00','17:00',12,'ativo'),
(2,2,'Apoio tecnico','2026-05-20','09:00','12:00',8,'ativo'),
(3,3,'Mediadora de leitura','2026-05-25','13:00','16:00',9,'ativo'),
(4,5,'Orientador de saude','2026-06-05','08:00','12:00',16,'ativo'),
(5,4,'Comunicacao social','2026-06-04','10:00','13:00',10,'ativo'),
(6,6,'Logistica de distribuicao','2026-06-08','07:00','11:00',20,'ativo'),
(7,7,'Apoio administrativo','2026-06-11','14:00','17:00',6,'ativo'),
(8,2,'Instrutor de tecnologia','2026-06-12','09:00','12:00',12,'ativo'),
(1,8,'Apoio pedagogico','2026-06-13','08:00','11:00',9,'ativo'),
(3,1,'Apoio leitura','2026-06-14','14:00','16:00',6,'ativo'),
(5,3,'Divulgacao comunitaria','2026-06-15','09:00','11:00',4,'ativo'),
(6,5,'Organizacao de insumos','2026-06-16','08:00','12:00',8,'ativo');

CREATE OR REPLACE VIEW vw_doacoes_por_projeto AS
SELECT p.id_projeto, p.nome AS nome_projeto, o.nome AS nome_ong,
       COUNT(d.id_doacao) AS quantidade_doacoes, COALESCE(SUM(d.valor), 0) AS total_doacoes
FROM projeto p
JOIN ong o ON o.id_ong = p.id_ong
LEFT JOIN doacao d ON d.id_projeto = p.id_projeto AND d.status <> 'cancelada'
GROUP BY p.id_projeto, p.nome, o.nome;

CREATE OR REPLACE VIEW vw_voluntarios_por_projeto AS
SELECT p.id_projeto, p.nome AS nome_projeto,
       COUNT(DISTINCT v.id_voluntario) AS total_voluntarios,
       COALESCE(SUM(vd.carga_horaria), 0) AS total_horas
FROM projeto p
LEFT JOIN voluntariado vd ON vd.id_projeto = p.id_projeto
LEFT JOIN voluntario v ON v.id_voluntario = vd.id_voluntario
GROUP BY p.id_projeto, p.nome;

CREATE OR REPLACE VIEW vw_recursos_por_projeto AS
SELECT p.id_projeto, p.nome AS nome_projeto,
       COUNT(r.id_recurso) AS total_recursos,
       COALESCE(SUM(r.valor_estimado), 0) AS valor_estimado_total
FROM projeto p
LEFT JOIN recurso r ON r.id_projeto = p.id_projeto
GROUP BY p.id_projeto, p.nome;

CREATE OR REPLACE VIEW vw_prestacao_contas_ong AS
SELECT o.id_ong, o.nome AS nome_ong,
       (SELECT COUNT(*) FROM projeto p WHERE p.id_ong = o.id_ong) AS total_projetos,
       (SELECT COUNT(*) FROM doacao d WHERE d.id_ong = o.id_ong AND d.status <> 'cancelada') AS total_doacoes,
       (SELECT COALESCE(SUM(d.valor), 0) FROM doacao d WHERE d.id_ong = o.id_ong AND d.status <> 'cancelada') AS valor_total_doacoes,
       (SELECT COUNT(*) FROM recurso r JOIN projeto p ON p.id_projeto = r.id_projeto WHERE p.id_ong = o.id_ong) AS total_recursos,
       (SELECT COALESCE(SUM(r.valor_estimado), 0) FROM recurso r JOIN projeto p ON p.id_projeto = r.id_projeto WHERE p.id_ong = o.id_ong) AS valor_estimado_recursos
FROM ong o;
